version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /scripts/docker/install-sh-smoke
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /scripts/docker/install-sh-nonroot
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /scripts/docker/install-sh-git-smoke
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /scripts/e2e
    schedule:
      interval: daily
